# Generated by Django 4.0.5 on 2022-06-11 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название категории')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='ссылка')),
            ],
            options={
                'verbose_name': 'категорию',
                'verbose_name_plural': 'категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products', verbose_name='картинка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('price', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='цена')),
                ('available', models.BooleanField(default=True, verbose_name='доступность')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='ссылка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='shop.category', verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('name',),
            },
        ),
    ]
