# Generated by Django 4.0.5 on 2022-06-11 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=200, null=True, verbose_name='бонус')),
            ],
            options={
                'verbose_name': 'бонусы',
                'verbose_name_plural': 'бонус',
            },
        ),
        migrations.CreateModel(
            name='HistoryResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'отклик',
                'verbose_name_plural': 'история откликов',
            },
        ),
        migrations.CreateModel(
            name='NecessarySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='необходимый навык')),
            ],
            options={
                'verbose_name': 'навыки',
                'verbose_name_plural': 'навык',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=200, null=True, verbose_name='требование')),
            ],
            options={
                'verbose_name': 'требования',
                'verbose_name_plural': 'требование',
            },
        ),
        migrations.CreateModel(
            name='TargetAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='высшее или среднее специальное образование', max_length=50, verbose_name='название целевой аудитории')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='ссылка')),
            ],
            options={
                'verbose_name': 'целевую аудиторию',
                'verbose_name_plural': 'целевые аудитории',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=200, null=True, verbose_name='задача')),
            ],
            options={
                'verbose_name': 'задачи',
                'verbose_name_plural': 'задача',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='наименование вакансии')),
                ('type', models.CharField(choices=[('full time', 'Полный день'), ('shift work', 'Сменный график'), ('internship', 'Стажировка'), ('side job', 'Подработка')], default='without payment', max_length=50, verbose_name='тип работы')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='начало мероприятия')),
                ('end_data', models.DateField(blank=True, null=True, verbose_name='конец мероприятия')),
                ('salary', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='заработная плата')),
                ('coins', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='размер бонусов')),
                ('urgency', models.CharField(choices=[('urgently', 'Срочно'), ('in a week', 'В течение недели'), ('in a month', 'В течение месяца')], default='urgently', max_length=30, verbose_name='срочность публикации')),
                ('location', models.CharField(blank=True, help_text='Место проведения мероприятия', max_length=100, null=True, verbose_name='местоположение')),
                ('email', models.EmailField(blank=True, help_text='E-mail для выгрузки откликов', max_length=254, null=True, verbose_name='эл.почта')),
                ('min_age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='минимальный возраст')),
                ('max_age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='максимальный возраст')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='ссылка')),
                ('is_paid_work', models.BooleanField(default=False, verbose_name='за работу платят')),
                ('there_are_coins', models.BooleanField(default=False, verbose_name='есть бонусы')),
                ('audience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner.targetaudience', verbose_name='целевая аудитория')),
                ('bonus', models.ManyToManyField(to='partner.bonus', verbose_name='бонусы волонтера')),
            ],
            options={
                'verbose_name': 'вакансию',
                'verbose_name_plural': 'вакансии',
            },
        ),
    ]
