# Generated by Django 4.0.5 on 2022-06-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TargetAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='высшее или среднее специальное образование', max_length=50, verbose_name='название целевой аудитории')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='ссылка')),
            ],
            options={
                'verbose_name': 'целевую аудиторию',
                'verbose_name_plural': 'целевые аудитории',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, verbose_name='название компании')),
                ('type_of_work', models.CharField(choices=[('without payment', 'Без оплаты'), ('permanent job', 'Постоянная'), ('internship', 'Стажировка'), ('side job', 'Подработка'), ('bonus', ' Бонус')], default='without payment', help_text='(временная, подработка, стажировка)', max_length=50, verbose_name='тип работы')),
                ('name', models.CharField(max_length=100, verbose_name='наименование вакансии')),
                ('terms', models.TextField(max_length=100, verbose_name='условия работы для волонтера')),
                ('tasks', models.TextField(help_text='Описание задач для волонтера', max_length=500, verbose_name='задачи')),
                ('description', models.TextField(help_text='требования к кандидатам и функционал', max_length=1000, verbose_name='описание')),
                ('salary', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='заработная плата')),
                ('bonus', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='размер бонусов')),
                ('motivation', models.TextField(blank=True, help_text='Описание мотивации волонтера', max_length=500, null=True, verbose_name='мотивация волонтера')),
                ('publication_urgency', models.CharField(choices=[('urgently', 'Срочно'), ('not urgently', 'Не срочно'), ('within a week', 'В течение недели'), ('within a month', 'В течение месяца')], default='urgently', max_length=30, verbose_name='срочность публикации')),
                ('start_date', models.DateTimeField(blank=True, help_text='Дата начала помощи', null=True, verbose_name='начало мероприятия')),
                ('end_data', models.DateTimeField(blank=True, help_text='Дата завершения набора на вакансию', null=True, verbose_name='конец мероприятия')),
                ('allowable_age', models.PositiveSmallIntegerField(blank=True, help_text='Подходящий возраст волонтера', null=True, verbose_name='возраст волонтера')),
                ('mail_for_response', models.EmailField(help_text='E-mail для выгрузки откликов по вакансии', max_length=254, verbose_name='эл.почта')),
                ('service', models.TextField(help_text='Питание, экипировка, подтверждение опыта в ЛКВ', max_length=200, verbose_name='сервисы для волонтера')),
                ('location', models.TextField(help_text='Место проведения мероприятия', max_length=50, verbose_name='местоположение')),
                ('participation', models.CharField(choices=[('online', 'Онлайн'), ('offline', 'Офлайн')], max_length=20, verbose_name='способ участия')),
                ('position', models.CharField(blank=True, max_length=50, null=True, verbose_name='роль волонтера/должность')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='ссылка')),
                ('image', models.ImageField(upload_to='vacancy/', verbose_name='картинка вакансии')),
            ],
            options={
                'verbose_name': 'вакансию',
                'verbose_name_plural': 'вакансии',
            },
        ),
    ]
