# Generated by Django 4.0.5 on 2022-06-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя организации')),
                ('unp', models.CharField(help_text='учётный номер плательщика', max_length=50, verbose_name='УНП')),
                ('phone', models.CharField(max_length=30, verbose_name='номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('photo', models.ImageField(upload_to='image/', verbose_name='фотография')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('description', models.TextField(max_length=500, verbose_name='описание')),
                ('slug', models.SlugField(unique=True, verbose_name='ссылка')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('reward', models.PositiveSmallIntegerField(help_text='количество баллов для волонтера', verbose_name='награда волонтера')),
                ('slug', models.SlugField(unique=True, verbose_name='ссылка')),
            ],
        ),
    ]
