# Generated by Django 4.0.5 on 2022-06-11 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('partner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='название компании'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='necessary_skills',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='необходимые навыки'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='region',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.administrativeregion', verbose_name='административный округ'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='sphere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.sphere', verbose_name='сфера деятельности'),
        ),
        migrations.AddField(
            model_name='task',
            name='vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.vacancy'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.vacancy'),
        ),
        migrations.AddField(
            model_name='project',
            name='vacancy',
            field=models.ForeignKey(blank=True, help_text='история вакансий', null=True, on_delete=django.db.models.deletion.PROTECT, to='partner.vacancy', verbose_name='вакансия'),
        ),
        migrations.AddField(
            model_name='historyresponse',
            name='vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.vacancy'),
        ),
        migrations.AddField(
            model_name='historyresponse',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bonus',
            name='vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.vacancy'),
        ),
    ]
