# Generated by Django 4.0.5 on 2022-06-09 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0001_initial'),
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.category'),
        ),
        migrations.AddField(
            model_name='project',
            name='vacancy',
            field=models.ManyToManyField(help_text='связь с таблицей вакансии', to='partner.vacancy'),
        ),
        migrations.AddField(
            model_name='organization',
            name='project',
            field=models.ManyToManyField(to='partner.project', verbose_name='проект организации'),
        ),
    ]
