# Generated by Django 4.0.5 on 2022-06-09 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('volunteer', '0001_initial'),
        ('users', '0001_initial'),
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.category'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='city',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.city'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requirement',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.vacancy'),
        ),
        migrations.AddField(
            model_name='project',
            name='vacancy',
            field=models.ForeignKey(help_text='История вакансий', on_delete=django.db.models.deletion.PROTECT, to='partner.vacancy'),
        ),
    ]
