# Generated by Django 4.0.5 on 2022-06-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_alter_vacancy_description_alter_vacancy_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='allowable_age',
            field=models.CharField(blank=True, help_text='Подходящий возраст волонтера', max_length=10, null=True, verbose_name='возраст волонтера'),
        ),
    ]
