# Generated by Django 4.0.5 on 2022-06-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_alter_historyresponse_options_remove_bonus_vacancy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='name',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='бонус'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='bonus',
            field=models.ManyToManyField(to='partner.bonus', verbose_name='бонусы волонтера'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=models.ManyToManyField(to='partner.requirement', verbose_name='требования'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='task',
            field=models.ManyToManyField(to='partner.task', verbose_name='задачи волонтера'),
        ),
    ]
